<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.Ng.AspNet.Auth.Basic" Version="0.31.2--ci.5" />
    <PackageReference Include="CK.IO.User.UserPassword" Version="28.0.1--ci.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.Ng.UserProfile\CK.Ng.UserProfile.csproj" />
  </ItemGroup>
</Project>