<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.IO.Actor" Version="0.44.0--ci.4" />
    <PackageReference Include="CK.Ng.Cris.AspNet.Auth" Version="0.56.0--ci.5" />
    <PackageReference Include="CK.Ng.Zorro.Basic" Version="0.8.0--ci.6" />
  </ItemGroup>
</Project>